### ISSUE TITLE
Calls to fill_XXX rather than getXXX in LevelGeometry

### ISSUE THREAD

**Issue by ululi1970** [MUON-CFD/SOMAR#3]
One thing is that fill_XXX seems to be used by functions that need to fill ghost layers. At least, by looking not too deeply at the call tree...

**Comment by ululi1970** [comment]
Well, my hunch was only partially correct. On a single level noncached calls to the metric elements are due to grids that include ghost layers (typically, 4 ghost points along each directions) a little over 50% of the time.

**Comment by EdSantilli** [comment]
I was able to get a 25% speed increase by making three simple changes. 
1. Use the get_ function rather than the fill_ function in  AMRNavierStokes::setGhostsScalar.
2. Ditto for AMRNavierStokes::setLambdaScalar.
3. At Gradient::singleBoxMacGrad:1019, comment out the fill_ call and replace with this...

``` C++
    // We need a SpaceDim-component FAB to be filled with Jgup^{a_gradDir,*}
    // at every point a_gradFab is to be calculated.
    // FArrayBox JgupFAB(a_gradFab.box(), SpaceDim);
    // a_levGeo.fill_Jgup(JgupFAB, a_gradDir);

    FArrayBox JgupFAB;
    {
        const FArrayBox& JgupCachedFAB = a_levGeo.getFCJgup()[a_di][a_gradDir];
        const Box& JgupCacheBox = JgupCachedFAB.box();

        if (JgupCacheBox.type() == a_edgeBox.type()) {
            if (JgupCacheBox.contains(a_edgeBox)) {
                JgupFAB.define(JgupCachedFAB.interval(), (FArrayBox&)JgupCachedFAB);
            } else {
                JgupFAB.define(a_gradFab.box(), SpaceDim);
                a_levGeo.fill_Jgup(JgupFAB, a_gradDir);
            }
        } else {
            JgupFAB.define(a_gradFab.box(), SpaceDim);
            a_levGeo.fill_Jgup(JgupFAB, a_gradDir);
        }
    }
```

I still need to test these changes with multiple levels.

**Comment by EdSantilli** [comment]
We can do even better by performing the check shown above in the LevelGeometry fill functions. The problem is that they operator on FArrayBoxes and do not receive the DataIndex. It might be economical to loop over the grids with a DataIterator and search for a grid that contains _all_ of the data we are looking for.

**Question**: If the data lives on a different processor, do you think we should just recalculate or perform a data exchange?

**Comment by ululi1970** [comment]
Good question. First of all, how "sticky" are Boxes w.r.t. the  process they run on? If I get it right, the scenario you envision is one in which a Box is reassigned to a different process. Depending on stickiness, that may not happen to often. Assuming that 
what we are talking about involves O(N) calculations, the cost of sending data may be larger
than recalculating... So my hunch would be to leave it as is. I will implement your changes and rerun it through the profiler..

**Comment by ululi1970** [comment]
I tested your fixes. First of all, for the first two calls, I did
FluxBox JgupFB(region, nJgupComp);
        JgupFB.copy(m_levGeoPtr->getFCJgup()[dit],region);
that is, I copy. I wonder if I could just do this instead
const FluxBox& JgupFB=m_levGeoPtr->getFCJgup90[dit];

which, if I get the c++ right, treats JgupFB as an alias, saving a copy... 

At any rate, doing what you suggest cut the calls to fill_bathymetry by 75% in a short
test run. Not bad, but consider that there are still 10,000 calls over three time steps. 
The run time went down quite a bit too.. Now I will test over multiple levels, and then 
rerun the profiler to see who's still calling fill_bathymetry..

**Comment by ululi1970** [comment]
Over 2 levels seems ok. Also, profiling indicates that the 3D Gauss Sidel subroutine is the top
time consumer, which I think makes sense.
I assume that you may want to do a few more tests before committing this to the main branch. 
Also, could you email me the input file you used for the beam generator runs? 
I would like to run the same but in 3D with an isolated bump. 
I went over the the PhysBC file that you created for the 2D cases, and I think it should work 
with very minor modifications in 3D, provided I read it right.
In the meanwhile, I am going to close this issue.

**Comment by EdSantilli** [comment]
Final point on this thread...

I noticed that you created a whatIsMyLevel function in DEMMap. This may lead to problems. (Come to think of it, this may provide a hint as to why the fill functions are called with such frequency.) Consider this 1D example...

**Level 1**: dx = 2.0 and there is a cached metric here. Call it JgupFAB1.
**Level 0**: dx = 8.0 and there is a cached metric here, too. Call it JgupFAB0.

Now, suppose we are performing a Poisson solve on level 1. There are many grids that are created for this solve. Here are a few...
**Level 1, MG depth 0**: dx = 2.0
**Level 1, MG depth 1**: dx = 4.0
**Level 1, MG depth 2**: dx = 8.0
**Level 1, MG depth 3**: dx = 16.0
and so on until we cannot coarsen anymore. Each of these MG depths will need metric data. So let's generate it...

**Level 1, MG depth 0**: whatIsMyLevel(2.0) gives level = 1, which is correct. Use JgupFAB1.
**Level 1, MG depth 1**: whatIsMyLevel(4.0) gives level = -1, which is also correct. This is not an AMR level! So, use a fill function.
**Level 1, MG depth 2**: whatIsMyLevel(8.0) gives level = 0, which is wrong. The grids on level 0 do not match the grids on level 1, MG depth 2. The grids have different extents and different processor assignments. We need to use MPI communication if we want to copy JgupFAB0, but the function that called whatIsMyLevel(8.0) does not know this. It was simply told that it is on level 0.
**Level 1, MG depth 3**: whatIsMyLevel(16.0) gives level = -1, which is correct again. Use a fill function.

This problem gets even more complicated in the advective code, where the data centering needs to be considered as well.

These issues are the whole reason fill_XXX functions were used instead of getXXX functions. However, as long as we use appropriate if() branching like in the code listed above, we can really fix things up well.

If you look at the code, you'll notice that I intentionally restricted the cached data to LevelGeometry. This is because LevelGeometry understands the AMR hierarchy and what grids live where. It may be a simpler option to use if() branching in the LevelGeometry::fill_XXX functions rather than GeoSourceInterface::fill_XXX functions. For example, if LevelGeometry::fill_Jgup uses a cache, then we automatically remove calls to many GeoSourceInterface functions including fill_gup and fill_J which in turn would have called fill_dXidx many times. I will try this and let you know what happens...

**Comment by ululi1970** [comment]
in DEMMap whatIsMyLevel is only meant to be used within DEMMap to pick the right interpolation from the cache stack. Each process caches the depth over the entire domain, over all levels expected based on maxLevel. What I am thinking is that provided (i) RealVect DX is known and (ii)  Box interpBox  is properly located within domain domainBox, I can pass the  cached data. The two MayDay calls in DEMMAp::fill_bathymetry  should trap  exceptions. I never proposed to use whatIsMyLevel for any other application. SHould I make it private and/or restrict its use, just to be safe?

**Comment by EdSantilli** [comment]
Ahh yes, I forgot that the cached FABs will extend throughout the domain on every proc. I'd make it protected, so if you ever make a child of DEMMap it will have access.

**Comment by ululi1970** [comment]
I'd rather keep it private, not sure it even should be defined as a separate function at all. 
Also, it does not appear that the MG ever issues requests that go all the way down to
DEMMap::fill_bathymetry. Here's why: In the tests, level 1 is refined 4x1x1. I assume the multigrid 
will require grids that are neither 1x1x1 nor 4x1x1, which if requested would trigger an exception in DEMMap that I do not get. 

On a related note, this is where algebraic multigrid methods may shine. If I understand 
correctly, coarsening/prolongation works on the matrix elements, rather 
than on the underlying geometric structure...  

Unrelated, to this, but...
Here's a thing that has been gnawing at me, and it regards point (ii) in my post above. 
Suppose I have
Domain A(...);
Domain B(...);
As subsets of Z^D, A and B may be the same. However, a priori they can be used to 
discretize two different (sub)manifolds. So there ought to be a way to tie a Box X to
either A or B, so that if Box X is in A and Box Y is in B, X&Y should be empty 
even though as subsets of Z^D their intersection may not be empty. Does it make sense?

**Comment by EdSantilli** [comment]
I understand your domain question, but there is no way to do this with BoxTools. Boxes only work in index space, so they understand index limits and staggering, but nothing else. They have no notion of what (sub)manifold they are discretizing. This same issue was bothering me about FArrayBoxes and LevelDatas. It would be nice to be able to tie metadata to these structures. In C++, there is a very robust way of doing so -- create a context class and hand it to the box. The context class can contain whatever metadata and additional functionality you like. Many people in the CSCI community have solved this problem in the past.

**Comment by ululi1970** [comment]
Did not know that the Climate Savers Computing Initiative was so involved with C++

**Comment by EdSantilli** [comment]
I cached dXidx and altered the fill_XXX functions to copy the cache when possible. I saw no speed increase at all. The 3 changes I listed above produced the most fruitful optimization. However, to pass a regression test, you have to make 2 more changes...
1. LevelGeometryBasics.cpp:75-76:

``` C++
const IntVect LevelGeometry::s_ghostVectFC = 4*IntVect::Unit;
const IntVect LevelGeometry::s_ghostVectCC = 4*IntVect::Unit;
```
1. Increase interpBox in DEMMap.cpp to include the new ghosts:

``` C++
interpBox.grow(IntVect(D_DECL(6,6,0)));
```

I'd like to start importing DEMMap and this cache update into the main repo.

**Comment by ululi1970** [comment]
Added the changes, and pushed on the branch. Should I issue a pull request?

**Comment by EdSantilli** [comment]
Yessir.
-Ed
